CREATE TABLE CATEGORY (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORY (name) VALUES ('Ceriais');
INSERT INTO CATEGORY (name) VALUES ('Frutas');
INSERT INTO CATEGORY (name) VALUES ('Doces');
INSERT INTO CATEGORY (name) VALUES ('Limpeza');
INSERT INTO CATEGORY (name) VALUES ('Utensilios');
INSERT INTO CATEGORY (name) VALUES ('Outros');